### ISSUE TITLE
I can't download the datatset, is there somthing wrong with the dataset?

### ISSUE THREAD

**Issue by syqzdy** [marckhoury/CGF#2]

**Comment by syqzdy** [comment]
Could you upload some test pcd?Thanks

**Comment by marckhoury** [comment]
It's likely lost forever unfortunately. It used to be sitting on an Intel server, but was moved out by someone without my knowledge. When I asked my contacts there to try and find it, only a small portion was recovered. The remainder is probably sitting on an Intel server, but I no longer have access to find it myself.

**Comment by marckhoury** [comment]
The dataset is back up and the link should now be working.

**Comment by qsisi** [comment]
> _No description provided._

Hello

Have you kept the dataset for now? The dataset is unavailable now.
